require(maps);require(maptools):require(spdep)
dpad <- scale(dsel <- USArrests[-c(2, 11), c(1, 2, 4)])
usa.m <- map("state", fill = TRUE, col = "transparent", plot = FALSE)
IDs <- sapply(strsplit(usa.m$names, ":"), function(x) x[1])
usa.pl <- map2SpatialPolygons(usa.m, IDs = IDs)
usa48.nb <- subset(poly2nb(usa.pl), c(rep(T, 7), F, rep(T, 41)))
nbc.e <- nbcosts(usa48.nb, dpad)
nbw.e <- nb2listw(usa48.nb, nbc.e, style = "B")
mst.e <- mstree(nbw.e)
res.e4 <- skater(mst.e[, 1:2], dpad, 3)
res.e5 <- skater(res.e4, dpad, 1)
res.e6 <- skater(res.e5, dpad, 1)
res.e7 <- skater(res.e6, dpad, 1)
usa.coord <- coordinates(usa.pl)
plot(usa.pl)
plot(res.e7,usa.coord,add=T)